apiVersion: apps/v1
kind: Deployment
metadata:
  name: categoryapi
spec:
  selector:
    matchLabels:
      app: categoryapi
  replicas: 2
  template:
    metadata:
      labels:
        app: categoryapi
    spec:
      containers:
      - name: categoryapi
        image: satishlakshmiudemy/category-api:latest
        ports:
        - containerPort: 9595
